app = 'home-chores-app'
primary_region = 'ord'

[build]
  [build.args]
    VITE_POCKETBASE_URL = ""

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[mounts]
  source = "pb_data"
  destination = "/pb/pb_data"
